### ISSUE TITLE
Add "View All" Button to Home Sliders

### ISSUE THREAD

**Issue by helloadib** [edrisranjbar/sammakquran#11]
Right now when you scroll through the sliders of the home page and you get to the end of it, there is no "View All" button to see more posts on that type.
@helloadib create the front-end part of the buttons.
@edrisranjbar Link them to their respective URL (I will mention you as soon as I'm done with the front-end.)

**Comment by edrisranjbar** [comment]
Thanks

**Comment by helloadib** [comment]
@edrisranjbar Yo bro, it's done.
It's on the other repo.
There are 2 buttons; one for the header of the carousel, another one as a whole slide.
Good luck!

**Comment by edrisranjbar** [comment]
##TODO:
- [ ] update style.css
- [ ] update theme version
- [ ] add `view all` button to video section (beside title & as an slider item)
- [ ] add `view all` button to audio section (beside title & as an slider item)
- [ ] add `view all` button to article section (beside title & as an slider item)

**Comment by edrisranjbar** [comment]
Hey @helloadib ; it is Done, you can test and tell  me if this issue is ready for being closed.

**Comment by helloadib** [comment]
@edrisranjbar Hi!
I checked it.
Everything works fine, I just changed a label and pushed it to this repo.
Please push to the main website.
