### ISSUE TITLE
Order of categories

### ISSUE THREAD

**Issue by helloadib** [edrisranjbar/sammakquran#14]
Hi
Please sort categories and playlists dynamically based on being recently updated.

Thanks.

**Comment by edrisranjbar** [comment]
## TODO:
there are steps to take in order to fix this issue:
- [ ] create a function to sort playlists
- [ ] create a function to sort categories
- [ ] call related functions in `index.php`, `category.php`,

**Comment by edrisranjbar** [comment]
That's done bro :)

**Comment by helloadib** [comment]
Yo bro;
I don't know why but it doesn't seem to work properly.
Take a look at it, please.
Thanks.
@edrisranjbar

**Comment by edrisranjbar** [comment]
@helloadib please test sorting functionality again
